name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3"
      - name: Install dependencies
        run: pip install 'octodns==1.11.0'
      - name: Deploy DNS changes
        run: octodns-sync --config-file=./config/production.yaml --doit
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
